# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlUP9UZl8fgO993Zcn8aftUuNUt3kNDZ
"""

def display_menu():
    print("Todo List Menu:")
    print("1. Add task")
    print("2. View tasks")
    print("3. Mark task as completed")
    print("4. Delete task")
    print("5. Exit")

def add_task(todo_list):
    tasks = input("Enter tasks separated by commas: ").split(',')
    for task in tasks:
        todo_list[task.strip()] = False
    print("Tasks added successfully!")

def view_tasks(todo_list):
    if not todo_list:
        print("No tasks in the list.")
    else:
        print("Tasks:")
        for index, task in enumerate(todo_list, start=1):
            status = "Completed" if todo_list[task] else "Not completed"
            print(f"{index}. {task} - {status}")

def mark_completed(todo_list):
    view_tasks(todo_list)
    task_index = int(input("Enter the number of the task to mark as completed: ")) - 1
    tasks = list(todo_list.keys())
    task = tasks[task_index]
    todo_list[task] = True
    print("Task marked as completed!")

def delete_task(todo_list):
    view_tasks(todo_list)
    task_index = int(input("Enter the number of the task to delete: ")) - 1
    tasks = list(todo_list.keys())
    task = tasks[task_index]
    del todo_list[task]
    print("Task deleted successfully!")

def main():
    todo_list = {}
    while True:
        display_menu()
        choice = input("Enter your choice: ")

        if choice == '1':
            add_task(todo_list)
        elif choice == '2':
            view_tasks(todo_list)
        elif choice == '3':
            mark_completed(todo_list)
        elif choice == '4':
            delete_task(todo_list)
        elif choice == '5':
            print("Exiting program...")
            break
        else:
            print("Invalid choice. Please enter a valid option.")

if __name__ == "__main__":
    main()

